on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        mkdir .ssh
        install -m 600 -D /dev/null ~/.ssh/id_rrr
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > .ssh/id_rrr
        chmod 700 .ssh/id_rrr
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        pwd
        ls .ssh/
        cat .ssh/id_rrr
    - name: connect and pull
      run: ssh -i .ssh/id_rrr ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
    - name: random stuff
      run: ssh -i .ssh/id_rrr ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && cd ../ && mkdir random_stuffs"
    - name: cleanups
      run: rm -rf .ssh/
    - name: maybe connect?
      run: ssh -i .ssh/id_rrr ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
    - name: check namespace
      run: pwd && cd && pwd && cd /home/ && ls
